dist: xenial
language: python
matrix:
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: 'pypy'
  - python: 'pypy3'
cache: pip
install:
  - pip install .[test]
script:
  - flake8 *.py
  - pytest run_tests.py
after_success:
  - pip install -q coverage==4.4 coveralls pytest-cov
  - pytest run_tests.py --cov flake8_isort --cov-report term-missing
  - coveralls
